"""create_tables

Revision ID: 8b84002e2246
Revises: 
Create Date: 2024-09-02 11:54:31.250384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b84002e2246'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    op.add_column('comments', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('photos', sa.Column('average_rating', sa.Float(), nullable=False))
    op.alter_column('photos', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_photos_description', table_name='photos')
    op.create_index(op.f('ix_photos_id'), 'photos', ['id'], unique=False)
    op.add_column('tags', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_constraint('tags_tag_name_key', 'tags', type_='unique')
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.drop_column('tags', 'tag_name')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'is_active')
    op.add_column('tags', sa.Column('tag_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.create_unique_constraint('tags_tag_name_key', 'tags', ['tag_name'])
    op.drop_column('tags', 'name')
    op.drop_index(op.f('ix_photos_id'), table_name='photos')
    op.create_index('ix_photos_description', 'photos', ['description'], unique=False)
    op.alter_column('photos', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('photos', 'average_rating')
    op.drop_column('comments', 'is_deleted')
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_table('ratings')
    # ### end Alembic commands ###
