"""Initial migration

Revision ID: a787b3e2ccc3
Revises: d96d27ce9b58
Create Date: 2024-09-03 23:47:01.844913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a787b3e2ccc3'
down_revision: Union[str, None] = 'd96d27ce9b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
