"""Initial migration

Revision ID: f982e7775046
Revises: f1214a2ee106
Create Date: 2024-08-30 18:15:55.193921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f982e7775046'
down_revision: Union[str, None] = 'f1214a2ee106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('average_rating', sa.Float(), nullable=False))
    op.create_index(op.f('ix_photos_id'), 'photos', ['id'], unique=False)
    op.add_column('tags', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_constraint('tags_tag_name_key', 'tags', type_='unique')
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.drop_column('tags', 'tag_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('tag_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.create_unique_constraint('tags_tag_name_key', 'tags', ['tag_name'])
    op.drop_column('tags', 'name')
    op.drop_index(op.f('ix_photos_id'), table_name='photos')
    op.drop_column('photos', 'average_rating')
    # ### end Alembic commands ###
